# Generated by Django 4.2 on 2025-05-17 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_easteregg_greetingcardtemplate_reward_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reward",
            name="actual_frame_image",
            field=models.ImageField(
                blank=True,
                help_text="รูปภาพกรอบโปรไฟล์จริง (PNG พื้นหลังโปร่งใส) ถ้าเป็นรางวัลประเภท Profile Frame",
                null=True,
                upload_to="rewards/frames/",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="active_profile_frame",
            field=models.ForeignKey(
                blank=True,
                help_text="กรอบโปรไฟล์ที่ผู้ใช้กำลังใช้งาน (ต้องเป็นประเภท 'profile_frame' และผู้ใช้ต้องแลกมาแล้ว)",
                limit_choices_to={"reward_type": "profile_frame"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activated_by_users",
                to="myapp.reward",
            ),
        ),
        migrations.AlterField(
            model_name="easteregg",
            name="points_reward",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="myapp.category",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="myapp.community",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="events/"),
        ),
        migrations.AlterField(
            model_name="pointactivitylog",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("daily_login", "Daily Login"),
                    ("profile_complete_basic", "Profile Basic Info Added"),
                    ("profile_complete_picture", "Profile Picture Uploaded"),
                    ("create_event", "Create Event"),
                    ("event_popular", "Popular Event Created"),
                    ("join_event", "Join Event"),
                    ("found_easter_egg", "Found Easter Egg"),
                    ("sent_greeting_card", "Sent Greeting Card"),
                    ("anniversary_signup", "Signup Anniversary"),
                    ("community_milestone", "Community Milestone Bonus"),
                    ("redeem_reward", "Redeem Reward"),
                    ("redeem_reward_failed_reversal", "Redeem Reward Failed Reversal"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="reward",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="รูปภาพ Preview สำหรับแสดงในร้านค้า",
                null=True,
                upload_to="rewards/previews/",
            ),
        ),
        migrations.AlterField(
            model_name="reward",
            name="reward_type",
            field=models.CharField(
                choices=[
                    ("badge", "Badge"),
                    ("profile_frame", "Profile Frame"),
                    ("discount_code", "Discount Code"),
                    ("digital_good", "Digital Good"),
                ],
                default="badge",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True, default="profiles/fw.png", null=True, upload_to="profiles/"
            ),
        ),
    ]
